routes/web.php
<?php

use Illuminate\Support\Facades\Route;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainPageController@index'  )->name('guest-page');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');



Route::group(['middleware' => 'auth'], function () {
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});
Route::group(['middleware' => ['auth'=>'admin']], function () {
    Route::get('CreateModel', 'CreateModelController@index')->name('CreateModel');
    Route::post('CreateModel', 'CreateModelController@insert');
    Route::get('Models', 'ModelsController@index')->name('Models');
    Route::resource('models', 'ModelsController');

    Route::get('Models/{id}/edit', 'ModelsController@edit')->name('models.edit');
    Route::put('Models/{id}', 'ModelsController@update')->name('models.update');

    Route::get('search', 'ModelsController@search');

});


Auth::routes();


Route::group(['middleware' => 'auth'], function () {
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});



Route::resource('modelis', 'ModelisController');Route::resource('modelis', 'modelisController');Route::resource('naujs', 'naujController');Route::resource('karts', 'kartController');

resources/views/Afterlogindashboard.blade.php
@extends('layouts.app', ['title' => __('Naujienos')])

@section('additional_header_content')

@endsection

@section('content')
    @include('users.partials.header', ['title' => __('Pagrindinis'),
             'class' => 'col-lg-12'])

    <div class="card card-stats mt-0 xl-500 bg-gradient-cyan">

        <div class="form-group  text-darker text-center" style="padding-top: 20px;">
            <h1><b> <label>Jūs Prisijungėte! Pažiūrėję į kairę matysite galimus funkcionalumus</label></b></h1>

        </div>

    </div>



    </div>
@endsection

resources/views/Modelis.blade.php
@section('content')
    @include('users.partials.header', ['title' => __('Apie mus'),
             'class' => 'col-lg-12'])

    <div style="padding:40px">

        <div class="heading-text el-text"><h1 class="h1"><span>TAISYKLĖS</span></h1></div>

        <div class="heading-text el-text"><h3 class="h3"><span>I. BENDROSIOS NUOSTATOS</span></h3></div>



@endsection

resources/views/Models.blade.php
@extends('layouts.app')

@section('additional_header_content')

@endsection

@section('content')
    @include('users.partials.header', ['title' => __('Formos'),
             'class' => 'col-lg-12'])

    <form class="input-group" action="{{url('search')}}" method="get" >
        <input  type="search" class="form-control rounded" placeholder="Įvesti formos pavadinimą" name="query">
        <button type="submit" class="btn btn-outline-primary">Ieškoti</button>
    </form>

    <table class="table table-hover table-dark table table-bordered  ">
        <thead class="bg-darker">
        <tr>
            <th style="text-align: center">Formos Id</th>
            <th style="text-align: center">Formos Pavadinimas</th>
            <th style="text-align: center">Redaguoti</th>
            <th style="text-align: center">Ištrinti</th>
        </tr>
        </thead>
        @foreach($Models as $model)
            <div class="row">
                <tbody id="container" >
                <div class="myClass">
                    <th style="vertical-align: middle; text-align:center" >
                        <a class=" text-bold text-white">{{ $model->id }}</a>
                    </th>
                    <th style="vertical-align: middle; text-align:center" >
                        <a class=" text-bold text-white">{{ $model->Model_Name }}</a>
                    </th>

                    <th style="text-align: center;vertical-align: middle; padding-bottom: 10px;width: 30px;">

                        <form action="{{ route('models.edit', $model->id) }}" id="edit_model" method="POST">
                            @csrf
                            @method('GET')
                            <button type="submit" class="btn btn-blue btn-sm">Redaguoti</button>

                        </form>
                    </th>

                    <th style="text-align: center;vertical-align: middle; padding-bottom: 10px;width: 30px;">

                        <form action="{{ route('models.destroy', $model->id) }}" id="delete_model" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger btn-sm">Ištrinti</button>

                        </form>
                    </th>
                </div>
                </tbody>

            </div>
        @endforeach
    </table>
    </div>


@endsection

resources/views/dashboard.blade.php
@extends('layouts.app', ['title' => __('Naujienos')])

@section('additional_header_content')

@endsection

@section('content')
    @include('users.partials.header', ['title' => __('Pagrindinis'),
             'class' => 'col-lg-12'])

    <div class="card card-stats mt-0 xl-500 bg-gradient-cyan">

        <div class="form-group  text-darker text-center" style="padding-top: 20px;">
            <h1><b> <label>Sveiki atvykę į Tomo Dunčiko puslapį. Čia rasite CRUD GENERATORIŲ, kuris padės jums sutaupyti
                        laiko programuojant!</label></b></h1>
            <p>
            <h2><b> <label> </label></b></h2></p>
            <h1><b> <label>Galimybė sukurti modelio, vaizdo, valdiklio ir migracijos failus vieno mygtuko
                        paspaudimu</label></b></h1>
            <h1><b> <label>Galimybė redaguoti ir ištrinti failus realiu laiku</label></b></h1>
            <h1><b> <label>Užtikrinta apsauga nuo pašalinių asmenų</label></b></h1>


        </div>

    </div>



    </div>
@endsection

resources/views/kart.blade.php
@section('content')
    @include('users.partials.header', ['title' => __('Apie mus'),
             'class' => 'col-lg-12'])

    <div style="padding:40px">

        <div class="heading-text el-text"><h1 class="h1"><span>TAISYKLĖS</span></h1></div>

        <div class="heading-text el-text"><h3 class="h3"><span>I. BENDROSIOS NUOSTATOS</span></h3></div>



@endsection